apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-app
  labels:
    app: balance-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: balance-app
  template:
    metadata:
      labels:
        app: balance-app
    spec:
      containers:
        - name: balance-app
          image: fintech-container/balance-app:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "Server=mssql-service;Database=mydatabase;User Id=sa;Password=YourStrong!Passw0rd;"
