apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-app
  labels:
    app: frontend-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-web-app
  template:
    metadata:
      labels:
        app: frontend-web-app
    spec:
      containers:
        - name: frontend-web-app
          image: fintech-container/frontend-web-app:latest
          ports:
            - containerPort: 6000
          env:
            - name: DATABASE_URL
              value: "Server=mssql-service;Database=mydatabase;UserId=sa;Password=YourStrong!Passw0rd;"