apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-app
  labels:
    app: transaction-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-app
  template:
    metadata:
      labels:
        app: transaction-app
    spec:
      containers:
        - name: transaction-app
          image: fintech-container/transaction-app:latest
          ports:
            - containerPort: 3003
          env:
            - name: DATABASE_URL
              value: "Server=mssql-service;Database=mydatabase;UserId=sa;Password=YourStrong!Passw0rd;"